"""
Plotlyst
Copyright (C) 2021  Zsolt Kovari

This file is part of Plotlyst.

Plotlyst is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Plotlyst is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

icons_registry = {
    "People": [
        "fa5.angry", "fa5.dizzy", "fa5.flushed", "fa5.frown", "fa5.frown-open", "fa5.grimace", "fa5.grin",
        "fa5.grin-alt", "fa5.grin-beam",
        "fa5.grin-beam-sweat", "fa5.grin-hearts", "fa5.grin-squint", "fa5.grin-squint-tears",
        "fa5.grin-stars", "fa5.grin-tears",
        "fa5.grin-tongue", "fa5.grin-tongue-squint",
        "fa5.grin-tongue-wink",
        "fa5.grin-wink", "fa5.kiss",
        "fa5.kiss-beam", "fa5.kiss-wink-heart",
        "fa5.laugh", "fa5.laugh-beam",
        "fa5.laugh-squint",
        "fa5.laugh-wink", "fa5.meh",
        "fa5.meh-blank",
        "fa5.meh-rolling-eyes", "fa5.sad-cry", "fa5.sad-tear", "fa5.smile", "fa5.smile-beam", "fa5.smile-wink",
        "fa5.surprise", "fa5.thumbs-down",
        "fa5.thumbs-up",
        "fa5.tired", "fa5.user", "fa5.user-circle",

        "fa5s.address-book", "fa5s.address-card",
        "fa5s.allergies", "fa5s.angry",
        "fa5s.baby", "fa5s.brain", "fa5s.hiking",
        "fa5s.child",
        "fa5s.female", "fa5s.male",
        "fa5s.people-carry",
        "fa5s.person-booth", "fa5s.portrait", "fa5s.pray", "fa5s.user-astronaut",
        "fa5s.user-friends", "fa5s.user-graduate", "fa5s.user-injured", "fa5s.user-lock", "fa5s.user-md",
        "fa5s.user-ninja",
        "fa5s.user-nurse",
        "fa5s.user-secret",
        "fa5s.user-shield", "fa5s.user-slash",
        "fa5s.user-tag",
        "fa5s.user-tie", "fa5s.users", "fa5s.users-cog", "fa5s.ice-cream", "fa5s.", "fa5s.",
        "fa5s.",
        "fa5s.",
        "fa5s.",
        "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.",
    ],
    "Animals & Nature": [
        "fa5.lemon", "fa5.moon", "fa5.snowflake", "fa5.sun",
        "fa5s.apple-alt", "mdi.bacteria", "mdi.bacteria-outline", "fa5s.bolt", "fa5s.bug", "fa5s.cat",
        "fa5s.crow", "fa5s.dog", "fa5s.dove", "fa5s.dragon", "fa5s.feather", "fa5s.feather-alt", "fa5s.fish",
        "fa5s.frog",
        "fa5s.hippo",
        "fa5s.horse", "fa5s.horse-head", "fa5s.kiwi-bird", "fa5s.otter",
        "fa5s.paw", "fa5s.spider", "fa5s.tree",
        "fa5s.wind",
        "fa5s.mountain",
        "fa5s.carrot", "fa5s.leaf", "fa5s.lemon", "fa5s.pepper-hot", "fa5s.seedling", "fa5s.water", "fa5s.", "fa5s.",
        "fa5s.cloud",
        "fa5s.cloud-meatball",
        "fa5s.cloud-moon",
        "fa5s.cloud-moon-rain",
        "fa5s.cloud-rain", "fa5s.cloud-showers-heavy", "fa5s.cloud-sun", "fa5s.cloud-sun-rain", "fa5s.meteor",
        "fa5s.moon",
        "fa5s.poo-storm", "fa5s.rainbow",
        "fa5s.smog",
        "fa5s.snowflake", "fa5s.sun",
        "fa5s.icicles", "fa5s.meteor", "fa5s.moon",
        "fa5s.pastafarianism", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
    ],
    "Sports and Activities": [
        "fa5.futbol", "fa5.life-ring",

        "fa5s.ambulance", "fa5s.baseball-ball", "fa5s.basketball-ball", "fa5s.bowling-ball", "fa5s.skating",
        "fa5s.skiing",
        "fa5s.skiing-nordic",
        "fa5s.snowboarding",
        "fa5s.running",
        "fa5s.skating", "fa5s.swimmer", "fa5s.walking", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.",
        "fa5s.", "fa5s.",
        "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
    ],
    "Travel and Places": [
        "fa5.building", "fa5.hospital", "fa5s.hospital-alt",

        "fa5s.archway", "fa5s.baby-carriage", "fa5s.bath", "fa5s.bed", "fa5s.bicycle", "fa5s.biking", "fa5s.tractor",
        "fa5s.igloo",
        "fa5s.snowplow",
        "fa5s.tram", "fa5s.bus", "fa5s.bus-alt", "fa5s.car", "fa5s.car-alt", "fa5s.car-crash", "fa5s.car-side",
        "fa5s.fighter-jet",
        "fa5s.helicopter",
        "fa5s.motorcycle",
        "fa5s.plane",
        "fa5s.rocket", "fa5s.ship",
        "fa5s.shopping-cart", "fa5s.shuttle-van",
        "fa5s.sleigh", "fa5s.space-shuttle",
        "fa5s.subway", "fa5s.taxi", "fa5s.tractor", "fa5s.train", "fa5s.tram", "fa5s.truck", "fa5s.truck-monster",
        "fa5s.truck-pickup", "fa5s.wheelchair",
        "fa5s.traffic-light",
        "fa5s.clinic-medical",
        "fa5s.home",
        "fa5s.hotel", "fa5s.industry", "fa5s.mosque", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.",
        "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.",
    ],
    "Objects": [
        "fa5.calendar", "fa5.calendar-alt", "fa5.clock", "fa5.compass", "fa5.envelope", "fa5.envelope-open", "fa5.gem",
        "fa5.hourglass", "fa5.lightbulb",
        "fa5.map", "fa5.money-bill-alt", "fa5.newspaper",
        "fa5.paper-plane", "fa5.trash-alt",

        "fa5s.air-freshener",
        "fa5s.anchor", "fa5s.ankh", "fa5s.archive", "fa5s.atlas", "fa5s.bacon", "fa5s.band-aid", "fa5s.bible", "fa5s.",
        "fa5s.beer",
        "fa5s.binoculars",
        "fa5s.birthday-cake",
        "fa5s.blender",
        "fa5s.bomb", "fa5s.bone", "fa5s.bong", "fa5s.book", "fa5s.book-dead", "fa5s.book-medical", "fa5s.book-open",
        "fa5s.box",
        "fa5s.box-open",
        "fa5s.bread-slice",
        "fa5s.briefcase",
        "fa5s.briefcase-medical", "fa5s.broom", "fa5s.brush", "fa5s.wine-bottle",
        "fa5s.umbrella", "fa5s.mitten", "fa5s.journal-whills", "fa5s.robot", "fa5s.satellite", "fa5s.satellite-dish",
        "fa5s.dice", "fa5s.dice-one",
        "fa5s.dice-two",
        "fa5s.dice-three", "fa5s.dice-four",
        "fa5s.dice-five",
        "fa5s.dice-six", "fa5s.dice-d6", "fa5s.dice-d20", "fa5s.cubes", "fa5s.cube", "fa5s.hammer", "fa5s.guitar",
        "fa5s.hamburger",
        "fa5s.hanukiah",
        "fa5s.hard-hat",
        "fa5s.hat-wizard", "fa5s.highlighter", "fa5s.oil-can", "fa5s.piggy-bank",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
    ],
    "Symbols": [
        "fa5.bell", "fa5.bell-slash", "fa5.comment", "fa5.copyright", "fa5.comments", "fa5.comment-dots",
        "fa5.dot-circle", "fa5.eye", "fa5.eye-slash",
        "fa5.heart", "fa5s.heart-broken", "fa5s.heartbeat",
        "fa5.image", "fa5.images", "fa5.question-circle",
        "fa5.registered", "fa5.star",
        "fa5.star-half", "fa5s.adjust",

        "fa5s.american-sign-language-interpreting",
        "fa5s.asterisk", "fa5s.at",
        "fa5s.atom", "fa5s.award",
        "fa5s.balance-scale",
        "fa5s.balance-scale-left", "fa5s.balance-scale-right", "fa5s.ban",
        "fa5s.biohazard",
        "fa5s.blind", "fa5s.braille", "fa5s.temperature-high",
        "fa5s.temperature-low", "fa5s.restroom", "fa5s.hand-spock", "fa5s.jedi", "fa5s.hashtag", "fa5s.", "fa5s.",
        "fa5s.icons",
        "fa5s.infinity", "fa5s.info",
        "fa5s.info-circle",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.", "fa5s.",
        "fa5s.", "fa5s.",
    ],

}
