"""
Plotlyst
Copyright (C) 2021  Zsolt Kovari

This file is part of Plotlyst.

Plotlyst is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Plotlyst is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

people = [
    "fa5.angry", "fa5.dizzy", "fa5.flushed", "fa5.frown", "fa5.frown-open", "fa5.grimace", "fa5.grin",
    "fa5.grin-alt", "fa5.grin-beam",
    "fa5.grin-beam-sweat", "fa5.grin-hearts", "fa5.grin-squint", "fa5.grin-squint-tears",
    "fa5.grin-stars", "fa5.grin-tears",
    "fa5.grin-tongue", "fa5.grin-tongue-squint",
    "fa5.grin-tongue-wink",
    "fa5.grin-wink", "fa5.kiss",
    "fa5.kiss-beam", "fa5.kiss-wink-heart",
    "fa5.laugh", "fa5.laugh-beam",
    "fa5.laugh-squint",
    "fa5.laugh-wink", "fa5.meh",
    "fa5.meh-blank",
    "fa5.meh-rolling-eyes", "fa5.sad-cry", "fa5.sad-tear", "fa5.smile", "fa5.smile-beam", "fa5.smile-wink",
    "fa5.surprise", "fa5.thumbs-down",
    "fa5.thumbs-up",
    "fa5.tired", "fa5.user", "fa5.user-circle",

    "fa5s.address-book", "fa5s.address-card",
    "fa5s.allergies", "fa5s.angry",
    "fa5s.baby", "fa5s.brain", "fa5s.hiking",
    "fa5s.child",
    "fa5s.female", "fa5s.male",
    "fa5s.people-carry",
    "fa5s.person-booth", "fa5s.portrait", "fa5s.pray", "fa5s.user-astronaut",
    "fa5s.user-friends", "fa5s.user-graduate", "fa5s.user-injured", "fa5s.user-lock", "fa5s.user-md",
    "fa5s.user-ninja",
    "fa5s.user-nurse",
    "fa5s.user-secret",
    "fa5s.user-shield", "fa5s.user-slash",
    "fa5s.user-tag",
    "fa5s.user-tie", "fa5s.users", "fa5s.users-cog", "fa5s.ice-cream", "", "",
    "",
    "",
    "",
    "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "",
]

food = [
    "fa5s.apple-alt",
    "fa5s.bacon",
    "fa5s.bone",
    "fa5s.bread-slice", "mdi.bread-slice", "mdi.bread-slice-outline",
    "fa5s.candy-cane",
    "fa5s.carrot",
    "fa5s.cheese",
    "fa5s.cloud-meatball",
    "fa5s.cookie",
    "fa5s.drumstick-bite",
    "fa5s.egg",
    "fa5s.fish",
    "fa5s.hamburger",
    "fa5s.hotdog",
    "fa5s.ice-cream",
    "fa5s.leaf",
    "fa5s.lemon",
    "fa5s.pepper-hot",
    "fa5s.pizza-slice",
    "fa5s.seedling",
    "fa5s.stroopwafel",

    "fa5s.beer",
    "mdi.beer",
    "mdi.beer-outline",
    "fa5s.cocktail",
    "fa5s.coffee",
    "fa5s.flask",
    "fa5s.glass-cheers",
    "fa5s.glass-martini",
    "fa5s.glass-martini-alt",
    "fa5s.glass-whiskey",
    "fa5s.mug-hot",
    "fa5s.wine-bottle",
    "fa5s.wine-glass",
    "fa5s.wine-glass-alt",
    "mdi.baguette",
    "mdi.bottle-tonic",
    "mdi.bottle-tonic-skull",
    "mdi.bottle-tonic-outline",
    "mdi.bottle-tonic-plus", "mdi.bottle-tonic-plus-outline", "mdi.bottle-tonic-skull-outline",
    "mdi.bottle-tonic-skull-outline", "mdi.bottle-wine", "mdi.bottle-wine-outline", "mdi.bowl", "mdi.bowl-mix", "", "",
    "mdi.bowl-mix-outline", "mdi.bowl-outline", "",
    "", "",
    "",
    "", "", "", "", "", "", "", "",
    "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",

]

nature = [
    "fa5.lemon", "fa5.moon", "fa5.snowflake", "fa5.sun",
    "fa5s.apple-alt", "mdi.bacteria", "mdi.bacteria-outline", "fa5s.bolt", "fa5s.bug", "fa5s.cat",
    "fa5s.crow", "fa5s.dog", "fa5s.dove", "fa5s.dragon", "fa5s.feather", "fa5s.feather-alt", "fa5s.fish",
    "fa5s.frog", "mdi.butterfly", "mdi.butterfly-outline",
    "fa5s.hippo",
    "fa5s.horse", "fa5s.horse-head", "fa5s.kiwi-bird", "fa5s.otter",
    "fa5s.paw", "fa5s.spider", "fa5s.tree",
    "fa5s.wind",
    "fa5s.mountain",
    "fa5s.carrot", "fa5s.leaf", "fa5s.lemon", "fa5s.pepper-hot", "fa5s.seedling", "fa5s.water", "",
    "mdi.bat",
    "fa5s.cloud",
    "fa5s.cloud-meatball",
    "fa5s.cloud-moon",
    "fa5s.cloud-moon-rain",
    "fa5s.cloud-rain", "fa5s.cloud-showers-heavy", "fa5s.cloud-sun", "fa5s.cloud-sun-rain", "fa5s.meteor",
    "fa5s.moon",
    "fa5s.poo-storm", "fa5s.rainbow",
    "fa5s.smog",
    "fa5s.snowflake", "fa5s.sun",
    "fa5s.icicles", "fa5s.meteor", "fa5s.moon",
    "fa5s.pastafarianism", "mdi.barley", "mdi.bee", "mdi.bee-flower", "mdi.beehive-outline", "mdi.brightness-3", "", "",
    "mdi.cactus", "",
    "",
    "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
]
sports = [
    "fa5.futbol", "fa5.life-ring",

    "fa5s.ambulance", "fa5s.baseball-ball", "fa5s.basketball-ball", "fa5s.bowling-ball", "fa5s.skating",
    "fa5s.skiing",
    "mdi.biathlon",

    "fa5s.skiing-nordic",
    "fa5s.snowboarding",
    "fa5s.running",
    "fa5s.skating", "fa5s.swimmer", "fa5s.swimming-pool", "fa5s.walking", "fa5s.chess", "fa5s.chess-bishop",
    "fa5s.chess-board",
    "fa5s.chess-king",
    "fa5s.chess-knight",
    "fa5s.chess-pawn",
    "fa5s.chess-queen",
    "fa5s.chess-rook",
    "fa5s.gamepad", "fa5s.biking",
    "mdi.baseball-bat", "",
    "mdi.baseball", "mdi.basketball", "mdi.basketball-hoop",
    "mdi.basketball-hoop-outline", "mdi.bowling", "", "", "", "", "", "", "", "", "", "",
    "mdi.bike", "mdi.bike-fast", "mdi.billiards", "mdi.billiards-rack", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
]
places = [
    "fa5.building", "fa5.hospital", "fa5s.hospital-alt",
    "mdi.bridge",
    "fa5s.archway", "fa5s.baby-carriage", "fa5s.bath", "fa5s.bed", "fa5s.bicycle", "fa5s.biking",
    "fa5s.tractor",
    "fa5s.igloo",
    "fa5s.snowplow",
    "fa5s.tram", "fa5s.bus", "fa5s.bus-alt", "mdi.bus", "mdi.bus-alert", "mdi.bus-articulated-end", "mdi.bus-school",
    "mdi.bus-side", "mdi.bus-stop",
    "fa5s.car",
    "fa5s.car-alt", "fa5s.car-crash",
    "fa5s.car-side",
    "fa5s.fighter-jet",
    "fa5s.helicopter",
    "fa5s.motorcycle",
    "mdi.air-purifier",
    "mdi.airbag",
    "mdi.airballoon",
    "mdi.airballoon-outline",
    "fa5s.plane",
    "mdi.airplane",
    "mdi.airplane-landing",
    "mdi.airplane-off",
    "mdi.airplane-takeoff",
    "mdi.airport",
    "fa5s.rocket", "fa5s.ship",
    "fa5s.shopping-cart", "fa5s.shuttle-van",
    "fa5s.sleigh", "fa5s.space-shuttle",
    "fa5s.subway", "fa5s.taxi", "fa5s.tractor", "fa5s.train", "fa5s.tram", "fa5s.truck", "fa5s.truck-monster",
    "fa5s.truck-pickup", "fa5s.wheelchair",
    "fa5s.traffic-light",
    "fa5s.clinic-medical",
    "fa5s.home",
    "fa5s.hotel", "fa5s.industry", "fa5s.mosque", "fa5s.vihara", "fa5s.place-of-worship", "fa5s.torii-gate",
    "fa5s.gopuram",
    "fa5s.synagogue",
    "mdi.barn",
    "mdi.beach",
    "",
    "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "",
]
objects = [
    "fa5.calendar", "fa5.calendar-alt", "fa5.clock", "fa5.compass", "fa5.envelope", "fa5.envelope-open",
    "fa5.gem", "mdi.pickaxe",
    "fa5.hourglass", "fa5.lightbulb",
    "fa5.map", "fa5.money-bill-alt", "fa5.newspaper",
    "fa5.paper-plane", "fa5.trash-alt",
    "mdi.calculator",
    "fa5s.air-freshener",
    "fa5s.anchor", "fa5s.ankh", "fa5s.archive", "fa5s.atlas", "fa5s.bacon", "fa5s.band-aid", "fa5s.bible",
    "fa5s.beer",
    "fa5s.blender",
    "fa5s.cocktail", "fa5s.coffee",
    "fa5s.flask",
    "fa5s.glass-cheers", "fa5s.glass-martini", "fa5s.glass-martini-alt", "fa5s.glass-whiskey",
    "fa5s.mug-hot", "fa5s.wine-bottle", "fa5s.wine-glass", "fa5s.wine-glass-alt",
    "fa5s.binoculars",
    "mdi.binoculars",
    "mdi.camera", "mdi.camera-account", 'mdi.camcorder', "mdi.camera-enhance", "mdi.camera-enhance-outline",
    "mdi.camera-gopro", "mdi.camera-wireless",
    "fa5s.birthday-cake", "mdi.cake", "mdi.cake-layered", "mdi.cake-variant",

    "fa5s.bomb", "fa5s.bone", "fa5s.bong", "fa5s.book", "fa5s.book-dead", "fa5s.book-medical",
    "fa5s.book-open",
    "fa5s.box",
    "fa5s.box-open",
    "fa5s.bread-slice",
    "fa5s.briefcase",
    "fa5s.briefcase-medical", "fa5s.broom", "mdi.broom", "fa5s.brush", "mdi.brush", "fa5s.wine-bottle",
    "mdi.bucket", "mdi.bucket-outline",
    "fa5s.umbrella", "fa5s.mitten", "fa5s.journal-whills", "fa5s.robot", "fa5s.satellite",
    "fa5s.satellite-dish", "mdi.bullet",
    "fa5s.dice", "fa5s.dice-one",
    "fa5s.dice-two",
    "fa5s.dice-three", "fa5s.dice-four",
    "fa5s.dice-five",
    "fa5s.dice-six", "fa5s.dice-d6", "fa5s.dice-d20", "fa5s.cubes", "fa5s.cube", "fa5s.hammer", "fa5s.brush",
    "fa5s.drafting-compass", "fa5s.dumpster", "fa5s.hard-hat",
    "fa5s.paint-roller",
    "fa5s.pencil-alt",
    "fa5s.pencil-ruler", "fa5s.ruler", "fa5s.ruler-combined", "fa5s.ruler-horizontal", "fa5s.ruler-vertical",
    "fa5s.screwdriver",
    "fa5s.toolbox",
    "fa5s.tools", "fa5s.wrench", "fa5s.guitar",
    "fa5s.hamburger",
    "fa5s.hanukiah",
    "fa5s.hard-hat",
    "fa5s.hat-wizard", "fa5s.highlighter", "fa5s.oil-can", "fa5s.piggy-bank",
    "fa5s.cookie", "fa5s.cookie-bite", "fa5s.mask", "", "", "",

    "fa5s.tv", "mdi.bed", "mdi.bed-double", "mdi.bed-double-outline", "mdi.bed-empty", "mdi.bed-king",
    "mdi.bed-king-outline", "mdi.bed-outline", "mdi.bed-queen", "mdi.bed-queen-outline", "mdi.bed-single",
    "mdi.bed-single-outline",
    "mdi.balloon", "mdi.basket",
    "mdi.bone",
    "mdi.bomb", "mdi.bolt", "mdi.bow-tie", "", "", "", "", "", "", "", "",
    "",
    "", "", "", "",
]
symbols = [

    "mdi.null",
    "mdi.numeric",
    "mdi.numeric-0",
    "mdi.numeric-0-box",
    "mdi.numeric-0-box-multiple",
    "mdi.numeric-0-box-multiple-outline",
    "mdi.numeric-0-box-outline",
    "mdi.numeric-0-circle",
    "mdi.numeric-0-circle-outline",
    "mdi.numeric-1",
    "mdi.numeric-1-box",
    "mdi.numeric-1-box-multiple",
    "mdi.numeric-1-box-multiple-outline",
    "mdi.numeric-1-box-outline",
    "mdi.numeric-1-circle",
    "mdi.numeric-1-circle-outline",
    "mdi.numeric-10",
    "mdi.numeric-10-box",
    "mdi.numeric-10-box-multiple",
    "mdi.numeric-10-box-multiple-outline",
    "mdi.numeric-10-box-outline",
    "mdi.numeric-10-circle",
    "mdi.numeric-10-circle-outline",
    "mdi.numeric-2",
    "mdi.numeric-2-box",
    "mdi.numeric-2-box-multiple",
    "mdi.numeric-2-box-multiple-outline",
    "mdi.numeric-2-box-outline",
    "mdi.numeric-2-circle",
    "mdi.numeric-2-circle-outline",
    "mdi.numeric-3",
    "mdi.numeric-3-box",
    "mdi.numeric-3-box-multiple",
    "mdi.numeric-3-box-multiple-outline",
    "mdi.numeric-3-box-outline",
    "mdi.numeric-3-circle",
    "mdi.numeric-3-circle-outline",
    "mdi.numeric-4",
    "mdi.numeric-4-box",
    "mdi.numeric-4-box-multiple",
    "mdi.numeric-4-box-multiple-outline",
    "mdi.numeric-4-box-outline",
    "mdi.numeric-4-circle",
    "mdi.numeric-4-circle-outline",
    "mdi.numeric-5",
    "mdi.numeric-5-box",
    "mdi.numeric-5-box-multiple",
    "mdi.numeric-5-box-multiple-outline",
    "mdi.numeric-5-box-outline",
    "mdi.numeric-5-circle",
    "mdi.numeric-5-circle-outline",
    "mdi.numeric-6",
    "mdi.numeric-6-box",
    "mdi.numeric-6-box-multiple",
    "mdi.numeric-6-box-multiple-outline",
    "mdi.numeric-6-box-outline",
    "mdi.numeric-6-circle",
    "mdi.numeric-6-circle-outline",
    "mdi.numeric-7",
    "mdi.numeric-7-box",
    "mdi.numeric-7-box-multiple",
    "mdi.numeric-7-box-multiple-outline",
    "mdi.numeric-7-box-outline",
    "mdi.numeric-7-circle",
    "mdi.numeric-7-circle-outline",
    "mdi.numeric-8",
    "mdi.numeric-8-box",
    "mdi.numeric-8-box-multiple",
    "mdi.numeric-8-box-multiple-outline",
    "mdi.numeric-8-box-outline",
    "mdi.numeric-8-circle",
    "mdi.numeric-8-circle-outline",
    "mdi.numeric-9",
    "mdi.numeric-9-box",
    "mdi.numeric-9-box-multiple",
    "mdi.numeric-9-box-multiple-outline",
    "mdi.numeric-9-box-outline",
    "mdi.numeric-9-circle",
    "mdi.numeric-9-circle-outline",
    "mdi.numeric-9-plus",
    "mdi.numeric-9-plus-box",
    "mdi.numeric-9-plus-box-multiple",
    "mdi.numeric-9-plus-box-multiple-outline",
    "mdi.numeric-9-plus-box-outline",
    "mdi.numeric-9-plus-circle",
    "mdi.numeric-9-plus-circle-outline",
    "mdi.numeric-negative-1",

    "mdi.alpha",
    "mdi.alpha-a",
    "mdi.alpha-a-box",
    "mdi.alpha-a-box-outline",
    "mdi.alpha-a-circle",
    "mdi.alpha-a-circle-outline",
    "mdi.alpha-b",
    "mdi.alpha-b-box",
    "mdi.alpha-b-box-outline",
    "mdi.alpha-b-circle",
    "mdi.alpha-b-circle-outline",
    "mdi.alpha-c",
    "mdi.alpha-c-box",
    "mdi.alpha-c-box-outline",
    "mdi.alpha-c-circle",
    "mdi.alpha-c-circle-outline",
    "mdi.alpha-d",
    "mdi.alpha-d-box",
    "mdi.alpha-d-box-outline",
    "mdi.alpha-d-circle",
    "mdi.alpha-d-circle-outline",
    "mdi.alpha-e",
    "mdi.alpha-e-box",
    "mdi.alpha-e-box-outline",
    "mdi.alpha-e-circle",
    "mdi.alpha-e-circle-outline",
    "mdi.alpha-f",
    "mdi.alpha-f-box",
    "mdi.alpha-f-box-outline",
    "mdi.alpha-f-circle",
    "mdi.alpha-f-circle-outline",
    "mdi.alpha-g",
    "mdi.alpha-g-box",
    "mdi.alpha-g-box-outline",
    "mdi.alpha-g-circle",
    "mdi.alpha-g-circle-outline",
    "mdi.alpha-h",
    "mdi.alpha-h-box",
    "mdi.alpha-h-box-outline",
    "mdi.alpha-h-circle",
    "mdi.alpha-h-circle-outline",
    "mdi.alpha-i",
    "mdi.alpha-i-box",
    "mdi.alpha-i-box-outline",
    "mdi.alpha-i-circle",
    "mdi.alpha-i-circle-outline",
    "mdi.alpha-j",
    "mdi.alpha-j-box",
    "mdi.alpha-j-box-outline",
    "mdi.alpha-j-circle",
    "mdi.alpha-j-circle-outline",
    "mdi.alpha-k",
    "mdi.alpha-k-box",
    "mdi.alpha-k-box-outline",
    "mdi.alpha-k-circle",
    "mdi.alpha-k-circle-outline",
    "mdi.alpha-l",
    "mdi.alpha-l-box",
    "mdi.alpha-l-box-outline",
    "mdi.alpha-l-circle",
    "mdi.alpha-l-circle-outline",
    "mdi.alpha-m",
    "mdi.alpha-m-box",
    "mdi.alpha-m-box-outline",
    "mdi.alpha-m-circle",
    "mdi.alpha-m-circle-outline",
    "mdi.alpha-n",
    "mdi.alpha-n-box",
    "mdi.alpha-n-box-outline",
    "mdi.alpha-n-circle",
    "mdi.alpha-n-circle-outline",
    "mdi.alpha-o",
    "mdi.alpha-o-box",
    "mdi.alpha-o-box-outline",
    "mdi.alpha-o-circle",
    "mdi.alpha-o-circle-outline",
    "mdi.alpha-p",
    "mdi.alpha-p-box",
    "mdi.alpha-p-box-outline",
    "mdi.alpha-p-circle",
    "mdi.alpha-p-circle-outline",
    "mdi.alpha-q",
    "mdi.alpha-q-box",
    "mdi.alpha-q-box-outline",
    "mdi.alpha-q-circle",
    "mdi.alpha-q-circle-outline",
    "mdi.alpha-r",
    "mdi.alpha-r-box",
    "mdi.alpha-r-box-outline",
    "mdi.alpha-r-circle",
    "mdi.alpha-r-circle-outline",
    "mdi.alpha-s",
    "mdi.alpha-s-box",
    "mdi.alpha-s-box-outline",
    "mdi.alpha-s-circle",
    "mdi.alpha-s-circle-outline",
    "mdi.alpha-t",
    "mdi.alpha-t-box",
    "mdi.alpha-t-box-outline",
    "mdi.alpha-t-circle",
    "mdi.alpha-t-circle-outline",
    "mdi.alpha-u",
    "mdi.alpha-u-box",
    "mdi.alpha-u-box-outline",
    "mdi.alpha-u-circle",
    "mdi.alpha-u-circle-outline",
    "mdi.alpha-v",
    "mdi.alpha-v-box",
    "mdi.alpha-v-box-outline",
    "mdi.alpha-v-circle",
    "mdi.alpha-v-circle-outline",
    "mdi.alpha-w",
    "mdi.alpha-w-box",
    "mdi.alpha-w-box-outline",
    "mdi.alpha-w-circle",
    "mdi.alpha-w-circle-outline",
    "mdi.alpha-x",
    "mdi.alpha-x-box",
    "mdi.alpha-x-box-outline",
    "mdi.alpha-x-circle",
    "mdi.alpha-x-circle-outline",
    "mdi.alpha-y",
    "mdi.alpha-y-box",
    "mdi.alpha-y-box-outline",
    "mdi.alpha-y-circle",
    "mdi.alpha-y-circle-outline",
    "mdi.alpha-z",
    "mdi.alpha-z-box",
    "mdi.alpha-z-box-outline",
    "mdi.alpha-z-circle",
    "mdi.alpha-z-circle-outline",

    "fa5.bell", "fa5.bell-slash", "fa5.comment", "fa5.copyright", "fa5.comments", "fa5.comment-dots",
    "fa5.dot-circle", "fa5.eye", "fa5.eye-slash",
    "fa5.heart", "fa5s.heart-broken", "fa5s.heartbeat",
    "fa5.image", "fa5.images", "fa5.question-circle",
    "fa5.registered", "fa5.star", "mdi.brain",
    "fa5.star-half", "fa5s.adjust",
    "mdi.bullseye", "mdi.bullseye-arrow",
    "fa5s.american-sign-language-interpreting",
    "fa5s.asterisk", "fa5s.at",
    "fa5s.atom", "fa5s.battery-empty",
    "fa5s.battery-full",
    "fa5s.battery-half",
    "fa5s.battery-quarter", "fa5s.battery-three-quarters",
    "fa5s.broadcast-tower", "fa5s.burn", "fa5s.charging-station", "fa5s.fan", "fa5s.fire", "fa5s.fire-alt",
    "fa5s.gas-pump",
    "fa5s.radiation",
    "fa5s.radiation-alt",
    "fa5s.solar-panel",

    "fa5s.award",
    "fa5s.balance-scale",
    "fa5s.balance-scale-left", "fa5s.balance-scale-right", "fa5s.ban",
    "fa5s.biohazard",
    "mdi.biohazard",
    "fa5s.blind", "fa5s.braille", "fa5s.temperature-high",
    "fa5s.temperature-low", "fa5s.restroom", "fa5s.hand-spock", "fa5s.jedi", "fa5s.hashtag", "", "",
    "fa5s.icons",
    "fa5s.infinity", "fa5s.info",
    "fa5s.info-circle",
    "fa5s.shapes", "fa5s.dollar-sign", "fa5s.euro-sign", "fa5s.hryvnia",
    "fa5s.lira-sign",
    "fa5s.money-bill",
    "fa5s.money-bill-alt", "fa5s.money-bill-wave", "fa5s.money-bill-wave-alt", "fa5s.money-check",
    "fa5s.money-check-alt", "fa5s.pound-sign", "fa5s.ruble-sign", "fa5s.rupee-sign", "fa5s.shekel-sign", "fa5s.tenge",
    "fa5s.won-sign", "fa5s.yen-sign",

    "fa5s.angle-double-down",
    "fa5s.angle-double-left",
    "fa5s.angle-double-right",
    "fa5s.angle-double-up",
    "fa5s.angle-down",
    "fa5s.angle-left",
    "fa5s.angle-right",
    "fa5s.angle-up",
    "fa5s.arrow-alt-circle-down",
    "fa5s.arrow-alt-circle-down",
    "fa5s.arrow-alt-circle-left",
    "fa5s.arrow-alt-circle-left",
    "fa5s.arrow-alt-circle-right",
    "fa5s.arrow-alt-circle-right",
    "fa5s.arrow-alt-circle-up",
    "fa5s.arrow-alt-circle-up",
    "fa5s.arrow-circle-down",
    "fa5s.arrow-circle-left",
    "fa5s.arrow-circle-right",
    "fa5s.arrow-circle-up",
    "fa5s.arrow-down",
    "fa5s.arrow-left",
    "fa5s.arrow-right",
    "fa5s.arrow-up",
    "fa5s.arrows-alt",
    "fa5s.arrows-alt-h",
    "fa5s.arrows-alt-v",
    "fa5s.caret-down",
    "fa5s.caret-left",
    "fa5s.caret-right",
    "fa5s.caret-square-down",
    "fa5s.caret-square-down",
    "fa5s.caret-square-left",
    "fa5s.caret-square-left",
    "fa5s.caret-square-right",
    "fa5s.caret-square-right",
    "fa5s.caret-square-up",
    "fa5s.caret-square-up",
    "fa5s.caret-up",
    "fa5s.cart-arrow-down",
    "fa5s.chart-line",
    "fa5s.chevron-circle-down",
    "fa5s.chevron-circle-left",
    "fa5s.chevron-circle-right",
    "fa5s.chevron-circle-up",
    "fa5s.chevron-down",
    "fa5s.chevron-left",
    "fa5s.chevron-right",
    "fa5s.chevron-up",
    "fa5s.cloud-download-alt",
    "fa5s.cloud-upload-alt",
    "fa5s.compress-arrows-alt",
    "fa5s.download",
    "fa5s.exchange-alt",
    "fa5s.expand-arrows-alt",
    "fa5s.external-link-alt",
    "fa5s.external-link-square-alt",
    "fa5s.hand-point-down",
    "fa5s.hand-point-down",
    "fa5s.hand-point-left",
    "fa5s.hand-point-left",
    "fa5s.hand-point-right",
    "fa5s.hand-point-right",
    "fa5s.hand-point-up",
    "fa5s.hand-point-up",
    "fa5s.hand-pointer",
    "fa5s.hand-pointer",

    "fa5s.allergies",
    "fa5s.fist-raised",
    "fa5s.hand-holding",
    "fa5s.hand-holding-heart",
    "fa5s.hand-holding-usd",
    "fa5s.hand-lizard",
    "fa5s.hand-middle-finger",
    "fa5s.hand-paper",
    "fa5s.hand-peace",
    "fa5s.hand-rock",
    "fa5s.hand-scissors",
    "fa5s.hand-spock",
    "fa5s.hands",
    "fa5s.hands-helping",
    "fa5s.handshake",
    "fa5s.praying-hands",
    "fa5s.thumbs-down",
    "fa5s.thumbs-down",
    "fa5s.thumbs-up",
    "fa5s.thumbs-up",

    "fa5s.history",
    "fa5s.level-down-alt",
    "fa5s.level-up-alt",
    "fa5s.location-arrow",
    "fa5s.long-arrow-alt-down",
    "fa5s.long-arrow-alt-left",
    "fa5s.long-arrow-alt-right",
    "fa5s.long-arrow-alt-up",
    "fa5s.mouse-pointer",
    "fa5s.play",
    "fa5s.random",
    "fa5s.recycle",
    "fa5s.redo",
    "fa5s.redo-alt",
    "fa5s.reply",
    "fa5s.reply-all",
    "fa5s.retweet",
    "fa5s.share",
    "fa5s.share-square",
    "fa5s.share-square",
    "fa5s.sign-in-alt",
    "fa5s.sign-out-alt",
    "fa5s.sort",
    "fa5s.sort-alpha-down",
    "fa5s.sort-alpha-down-alt",
    "fa5s.sort-alpha-up",
    "fa5s.sort-alpha-up-alt",
    "fa5s.sort-amount-down",
    "fa5s.sort-amount-down-alt",
    "fa5s.sort-amount-up",
    "fa5s.sort-amount-up-alt",
    "fa5s.sort-down",
    "fa5s.sort-numeric-down",
    "fa5s.sort-numeric-down-alt",
    "fa5s.sort-numeric-up",
    "fa5s.sort-numeric-up-alt",
    "fa5s.sort-up",
    "fa5s.sync",
    "fa5s.sync-alt",
    "fa5s.text-height",
    "fa5s.text-width",
    "fa5s.undo",
    "fa5s.undo-alt",
    "fa5s.upload",

    "fa5s.genderless",
    "fa5s.mars",
    "fa5s.mars-double",
    "fa5s.mars-stroke",
    "fa5s.mars-stroke-h",
    "fa5s.mars-stroke-v",
    "fa5s.mercury",
    "fa5s.neuter",
    "fa5s.transgender",
    "fa5s.transgender-alt",
    "fa5s.venus",
    "fa5s.venus-double",
    "fa5s.venus-mars",

    "fa5s.ghost", "fa5s.skull-crossbones",
    "fa5s.tint", "fa5s.tint-slash", "fa5s.infinity", "fa5s.peace",

    "fa5s.bullseye",
    "fa5s.check-circle",
    "fa5s.circle",
    "fa5s.dot-circle",
    "fa5s.microphone",
    "fa5s.microphone-slash",
    "fa5s.star",
    "fa5s.star-half",
    "fa5s.star-half-alt",
    "fa5s.toggle-off",
    "fa5s.toggle-on",
    "fa5s.wifi",

    "mdi.alarm",
    "mdi.alarm-bell",
    "mdi.alarm-check",
    "mdi.alarm-light",
    "mdi.alarm-light-outline",
    "mdi.alarm-multiple",
    "mdi.alarm-note",
    "mdi.alarm-note-off",
    "mdi.alarm-off",
    "mdi.alarm-plus",
    "mdi.alarm-snooze",
    "mdi.album",
    "mdi.alert",
    "mdi.alert-box",
    "mdi.alert-box-outline",
    "mdi.alert-circle",
    "mdi.alert-circle-check",
    "mdi.alert-circle-check-outline",
    "mdi.alert-circle-outline",
    "mdi.alert-decagram",
    "mdi.alert-decagram-outline",
    "mdi.alert-octagon",
    "mdi.alert-octagon-outline",
    "mdi.alert-octagram",
    "mdi.alert-octagram-outline",
    "mdi.alert-outline",
    "mdi.alert-rhombus",
    "mdi.alert-rhombus-outline",
    "mdi.alien",
    "mdi.alien-outline",

    "mdi.allergy", "", "", "", "", "",
    "mdi.arm-flex",
    "mdi.arm-flex-outline",
    "", "", "", "", "", "", "", "", "", "", "",
    "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "",
    "",
    "", "", "", "", "", "", "", "", "", "", "",
    "",
    "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "",
    "",
    "", "",
]

icons_registry = {
    'People': people,
    'Food': food,
    'Animals & Nature': nature,
    'Sports & Activities': sports,
    'Travel & Places': places,
    'Objects': objects,
    'Symbols': symbols,
}
